services:
    php:
        container_name: php-container
        build: ./php
        volumes:
            - ./php:/var/www/html
    nginx:
        container_name: nginx-container
        image: nginx:1.27.0
        volumes:
            - ./php:/var/www/html
            - ./nginx:/etc/nginx/conf.d
        ports:
            - 80:80
    db:
        container_name: db-container
        image: mariadb:11.2.4
        restart: always
        volumes:
            - ./data/db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=docker
            - MYSQL_USER=user
            - MYSQL_PASSWORD=userpassword
            - MYSQL_ROOT_PASSWORD=rootpassword
